/**
 * Catalog data layer. Loads data/catalog.json (the aggregate the upstream
 * pipeline generates daily from the makers' Google Docs), normalizes it, and
 * assigns URL slugs. Loaded once per build and shared by every page.
 */
import { readFile } from 'node:fs/promises';
import path from 'node:path';

// Resolve from the project root (where astro runs), not this module's
// location: the bundled chunk's directory depth changes between Astro
// versions and build modes.
const dataDir = path.resolve(process.cwd(), 'data');

export function slugify(name) {
  return (
    name
      .toLowerCase()
      .normalize('NFKD')
      .replace(/[̀-ͯ]/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'unnamed'
  );
}

/** Join a path onto Astro's BASE_URL ('/' locally, '/ka-mirror' on Pages). */
export function withBase(p) {
  const base = import.meta.env.BASE_URL.replace(/\/+$/, '');
  return `${base}${p.startsWith('/') ? p : `/${p}`}`;
}

const CDN = 'https://cdn.keycap-archivist.com/keycaps';
/** CDN image variants generated by the upstream pipeline. */
export const img = {
  thumb: (id) => `${CDN}/250/${id}.jpg`,
  large: (id) => `${CDN}/720/${id}.jpg`,
  full: (id) => `${CDN}/${id}.jpg`,
};

/** "ka_from_XX" nationality code → flag emoji. */
export function flagEmoji(code) {
  if (!code || !/^[a-z]{2}$/i.test(code)) return '';
  return String.fromCodePoint(
    ...[...code.toUpperCase()].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65)
  );
}

function coverOf(sculpt) {
  return (
    sculpt.colorways.find((c) => c.isCover && c.img) ||
    sculpt.colorways.find((c) => c.img) ||
    null
  );
}

let cache = null;

export async function getCatalog() {
  if (cache) return cache;

  let makers, revision;
  try {
    makers = JSON.parse(await readFile(path.join(dataDir, 'catalog.json'), 'utf8'));
  } catch {
    throw new Error('data/catalog.json not found — run `npm run fetch-data` first.');
  }
  try {
    revision = JSON.parse(await readFile(path.join(dataDir, 'revision.json'), 'utf8'));
  } catch {
    revision = { revision: 'unknown', fetchedAt: null };
  }

  // Skip malformed upstream entries rather than failing the whole build.
  const cleanName = (name) => (typeof name === 'string' && name.trim()) || 'Unnamed';
  let skipped = 0;
  makers = makers.filter((maker) => {
    if (!maker || typeof maker !== 'object' || !maker.id) {
      skipped++;
      return false;
    }
    maker.name = cleanName(maker.name);
    const sculpts = Array.isArray(maker.sculpts) ? maker.sculpts : [];
    maker.sculpts = sculpts.filter((sculpt) => {
      if (!sculpt || typeof sculpt !== 'object' || !sculpt.id) {
        skipped++;
        return false;
      }
      sculpt.name = cleanName(sculpt.name);
      const colorways = Array.isArray(sculpt.colorways) ? sculpt.colorways : [];
      // Colorway images key off the id, so id-less colorways are unusable.
      sculpt.colorways = colorways.filter((c) => c && typeof c === 'object' && c.id);
      skipped += colorways.length - sculpt.colorways.length;
      return true;
    });
    return true;
  });
  if (skipped) console.warn(`catalog: skipped ${skipped} malformed entries`);

  // Tie-break on id so duplicate-name slugs stay stable across builds.
  makers.sort((a, b) => a.name.localeCompare(b.name, 'en') || a.id.localeCompare(b.id));

  const makerSlugs = new Set();
  for (const maker of makers) {
    let slug = slugify(maker.name);
    if (makerSlugs.has(slug)) slug = `${slug}-${maker.id}`;
    makerSlugs.add(slug);
    maker.slug = slug;
    maker.url = `/maker/${slug}/`;

    const sculptSlugs = new Set();
    maker.sculpts.sort(
      (a, b) => a.name.localeCompare(b.name, 'en') || a.id.localeCompare(b.id)
    );
    for (const sculpt of maker.sculpts) {
      let sSlug = slugify(sculpt.name);
      if (sculptSlugs.has(sSlug)) sSlug = `${sSlug}-${sculpt.id}`;
      sculptSlugs.add(sSlug);
      sculpt.slug = sSlug;
      sculpt.url = `${maker.url}${sSlug}/`;
      sculpt.cover = coverOf(sculpt);
    }
    maker.cover = maker.sculpts.map((s) => s.cover).find(Boolean) || null;
    maker.colorwayCount = maker.sculpts.reduce((n, s) => n + s.colorways.length, 0);
  }

  cache = {
    makers,
    revision,
    stats: {
      makers: makers.length,
      sculpts: makers.reduce((n, m) => n + m.sculpts.length, 0),
      colorways: makers.reduce((n, m) => n + m.colorwayCount, 0),
    },
  };
  return cache;
}
